apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::115509430977:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1RA9UNW46R2P1
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::115509430977:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-08T23:14:40Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1671"
  uid: 59fe908d-9c05-4abc-a8fa-22301867f5ae
